ALTER TABLE sessions 
ADD COLUMN IF NOT EXISTS meeting_link VARCHAR(512) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS meeting_provider VARCHAR(50) DEFAULT 'google_meet',
ADD COLUMN IF NOT EXISTS meeting_status VARCHAR(50) DEFAULT 'NOT_CREATED';
